version: '3'

volumes:
  pg_data:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user"]
    restart: unless-stopped

  backend:
    container_name: backend
    image: daniilfedotov/ctrade_backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    command:
      - /bin/sh
      - "/app/entrypoint.sh"
    ports:
      - "8000:8000"
    restart: unless-stopped

  tg_bot:
    container_name: tg_bot
    image: daniilfedotov/ctrade_tg_bot
    env_file: ./tg_bot/.env
    depends_on:
      - backend
    restart: unless-stopped

  trading:
    container_name: trading
    image: daniilfedotov/ctrade_trading
    env_file: ./trading/.env
    depends_on:
      - backend
    restart: unless-stopped