# Generated by Django 5.0 on 2024-03-06 10:00

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='Trade opening date')),
                ('closed', models.BooleanField(default=False, verbose_name='Status of deal')),
                ('quantity', models.FloatField(verbose_name='Quantity purchased')),
                ('purchase_price', models.FloatField(verbose_name='Trade entry price')),
                ('selling_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Trade exit price')),
                ('revenue', models.FloatField(blank=True, default=None, null=True, verbose_name='Revenue for deal')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('top', models.FloatField(verbose_name='Grid top border.')),
                ('bottom', models.FloatField(verbose_name='Grid bottom border.')),
                ('number_of_levels', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Number of grid levels.')),
                ('deposit', models.FloatField(verbose_name='Deposit for strategy.')),
                ('installed', models.BooleanField(default=False, verbose_name='Status of grid.')),
                ('step', models.FloatField(blank=True, default=None, null=True, verbose_name='Grid step.')),
                ('order_size', models.FloatField(blank=True, default=None, null=True, verbose_name='Amount of currency per order.')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Buy order'), ('sell', 'Sell order')], max_length=4, verbose_name='Order type.')),
                ('order_id', models.CharField(max_length=20, verbose_name='Exchange order id.')),
                ('price', models.FloatField(verbose_name='Order price.')),
                ('quantity', models.FloatField(verbose_name='Number of coins in the order.')),
                ('inverse', models.BooleanField(default=False, verbose_name='Indicates an order that goes beyond the original grid.')),
                ('deal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.deal', verbose_name='Related deal.')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='deals.grid', verbose_name='Grid-parent.')),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Trading bot creation date')),
                ('working', models.BooleanField(default=False, verbose_name='Status of trading bot')),
                ('initial_deposit', models.FloatField(blank=True, default=None, null=True, verbose_name='Trading bot starting deposit')),
                ('current_deposit', models.FloatField(blank=True, default=None, null=True, verbose_name='Trading bot current deposit')),
                ('revenue', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('current_deposit'), '-', models.F('initial_deposit')), output_field=models.FloatField(), verbose_name='Revenue for trading bot')),
                ('market', models.CharField(choices=[('S', 'Spot'), ('F', 'Futures')], default='S', max_length=20, verbose_name='The market where the bot trades')),
                ('exchange', models.CharField(max_length=20, verbose_name='Exchange for trading.')),
                ('lock', models.FloatField(blank=True, default=None, null=True, verbose_name='Amount of locked assets.')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.grid', verbose_name='Grid settings for trading.')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.trader', verbose_name='Trader who made the deal'),
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_precision', models.IntegerField(verbose_name='Price precision for a trading pair in decimal places.')),
                ('quantity_precision', models.IntegerField(verbose_name='Quantity precision for a trading pair in decimal places.')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.currency', verbose_name='Linked model for a currency.')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.token', verbose_name='Linked model for a token.')),
            ],
        ),
        migrations.AddField(
            model_name='grid',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.tradingpair', verbose_name='Ticker of the coin being traded.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.tradingpair', verbose_name='Ticker of the coin being traded.'),
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('token', 'currency'), name='tradingpair_unique'),
        ),
    ]
