# Generated by Django 5.0 on 2024-02-14 11:42

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Trading bot creation date')),
                ('working', models.BooleanField(default=False, verbose_name='Status of trading bot')),
                ('initial_deposit', models.FloatField(verbose_name='Trading bot starting deposit')),
                ('current_deposit', models.FloatField(blank=True, null=True, verbose_name='Trading bot current deposit')),
                ('revenue', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('current_deposit'), '-', models.F('initial_deposit')), output_field=models.FloatField(), verbose_name='Revenue for trading bot')),
                ('market', models.CharField(choices=[('S', 'Spot'), ('F', 'Futures')], max_length=20, verbose_name='The market where the bot trades')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='Trade opening date')),
                ('closed', models.BooleanField(default=False, verbose_name='Status of deal')),
                ('ticker', models.CharField(max_length=20, verbose_name='Coin ticker')),
                ('purchase_price', models.FloatField(verbose_name='Trade entry price')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Trade exit price')),
                ('revenue', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('selling_price'), '-', models.F('purchase_price')), output_field=models.FloatField(), verbose_name='Revenue for deal')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.trader', verbose_name='Trader who made the deal')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
